<a href="https://colab.research.google.com/github/muhammadabbas2201/First-project/blob/main/data_preprocessing_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import scipy as stats
from warnings import filterwarnings
filterwarnings('ignore')

In [ ]:
file_path = '/content/drive/MyDrive/sample_dataset_1000.csv'
df = pd.read_csv(file_path)

In [ ]:
df.dtypes

ID                int64
Name             object
Age               int64
Gender           object
Salary          float64
Joining Date     object
Is Active          bool
Comments         object
dtype: object

In [ ]:
df_cleaned = df.drop_duplicates()

In [ ]:
df_cleaned.head()

,ID,Name,Age,Gender,Salary,Joining Date,Is Active,Comments
0,1,Paul,25,Female,90041.86,2017-01-31,False,Creative
1,2,Paul,31,Male,90285.02,2019-05-29,False,Needs Improvement
2,3,Rachel,30,Male,84321.65,2022-12-14,False,Hardworking
3,4,Bob,45,Male,68189.99,2023-09-05,True,Fast Learner
4,5,Eve,34,Male,35428.35,2018-05-19,True,Dedicated

In [ ]:
df_cleaned.isnull().sum()

ID              0
Name            0
Age             0
Gender          0
Salary          0
Joining Date    0
Is Active       0
Comments        0
dtype: int64

In [ ]:
df_cleaned['Salary'].fillna(df_cleaned['Salary'].mean(),inplace = True)
df_cleaned['Age'].fillna(df_cleaned['Age'].mean(), inplace = True)
# inplace

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_cleaned[['Age','Salary']]=scaler.fit_transform(df_cleaned[['Age','Salary']])
df_cleaned[['Age','Salary']].head()

     Age    Salary
0  0.125  0.667930
1  0.275  0.670636
2  0.250  0.604271
3  0.625  0.424746
4  0.350  0.060150

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_cleaned[['Age','Salary']]=scaler.fit_transform(df_cleaned[['Age','Salary']])
df_cleaned[['Age','Salary']].head()

        Age    Salary
0 -1.353353  0.580768
1 -0.843392  0.590183
2 -0.928385  0.359284
3  0.346519 -0.265329
4 -0.588411 -1.533850

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_cleaned['Gender_encoded']=le.fit_transform(df_cleaned['Gender'])
df_cleaned[['Gender','Gender_encoded']].head()

   Gender  Gender_encoded
0  Female               0
1    Male               1
2    Male               1
3    Male               1
4    Male               1

In [ ]:
import pandas as pd
df_cleaned = pd.get_dummies(df_cleaned,drop_first=True)
print(df_cleaned.head())

   ID       Age    Salary  Is Active  (Gender, Gender_encoded)  \
0   1 -1.353353  0.580768      False                         0
1   2 -0.843392  0.590183      False                         1
2   3 -0.928385  0.359284      False                         1
3   4  0.346519 -0.265329       True                         1
4   5 -0.588411 -1.533850       True                         1

   Gender_encoded  Name_Bob  Name_Charlie  Name_David  Name_Eve  ...  \
0               0     False         False       False     False  ...
1               1     False         False       False     False  ...
2               1     False         False       False     False  ...
3               1      True         False       False     False  ...
4               1     False         False       False      True  ...

   Comments_Great Team Player  Comments_Hardworking  Comments_Innovative  \
0                       False                 False                False
1                       False                 False                False
2                       False                  True                False
3                       False                 False                False
4                       False                 False                False

   Comments_Logical  Comments_Motivated  Comments_Needs Improvement  \
0             False               False                       False
1             False               False                        True
2             False               False                       False
3             False               False                       False
4             False               False                       False

   Comments_Passionate  Comments_Punctual  Comments_Reliable  \
0                False              False              False
1                False              False              False
2                False              False              False
3                False              False              False
4                False              False              False

   Comments_Versatile
0               False
1               False
2               False
3               False
4               False

[5 rows x 909 columns]

In [ ]:
from scipy.stats import zscore
import numpy as np
z_scores = np.abs(zscore(df_cleaned[['Age','Salary']]))
outliers = (z_scores > 3).any(axis = 1)
df_no_outliers = df_cleaned[~outliers]
df_no_outliers.head()

,ID,Age,Salary,Is Active,"(Gender, Gender_encoded)",Gender_encoded,Name_Bob,Name_Charlie,Name_David,Name_Eve,...,Comments_Great Team Player,Comments_Hardworking,Comments_Innovative,Comments_Logical,Comments_Motivated,Comments_Needs Improvement,Comments_Passionate,Comments_Punctual,Comments_Reliable,Comments_Versatile
0,1,-1.353353,0.580768,False,0,0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2,-0.843392,0.590183,False,1,1,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,3,-0.928385,0.359284,False,1,1,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,4,0.346519,-0.265329,True,1,1,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,5,-0.588411,-1.533850,True,1,1,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
file_path = '/content/drive/MyDrive/sample_dataset_1000.csv'
df= pd.read_csv(file_path)

In [ ]:
print("\nDataset Preview:")
print(df.head())

Dataset Preview:
   ID    Name  Age  Gender    Salary Joining Date  Is Active  \
0   1    Paul   25  Female  90041.86   2017-01-31      False
1   2    Paul   31    Male  90285.02   2019-05-29      False
2   3  Rachel   30    Male  84321.65   2022-12-14      False
3   4     Bob   45    Male  68189.99   2023-09-05       True
4   5     Eve   34    Male  35428.35   2018-05-19       True

            Comments
0           Creative
1  Needs Improvement
2        Hardworking
3       Fast Learner
4          Dedicated

In [ ]:
print(df.columns)

Index(['ID', 'Name', 'Age', 'Gender', 'Salary', 'Joining Date', 'Is Active',
       'Comments'],
      dtype='object')

In [ ]:
df.columns=['ID', 'Name', 'Age', 'Gender', 'Salary', 'Joining Date', 'Is Active',
       'Comments']
print(df.columns)

Index(['ID', 'Name', 'Age', 'Gender', 'Salary', 'Joining Date', 'Is Active',
       'Comments'],
      dtype='object')

In [ ]:
df.dtypes

ID                int64
Name             object
Age               int64
Gender           object
Salary          float64
Joining Date     object
Is Active          bool
Comments         object
dtype: object

In [ ]:
numeric_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()
numeric_cols.remove('ID')
print(numeric_cols)

['Age', 'Salary']

In [ ]:
X = df[['Age']]
Y = df['Salary']

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
#Display model coefficient
print("\nmodel cofficient")
print(f'intercept:{model.intercept_}')
print(f"slope:{model.coef_[0]}")

model cofficient
intercept:78099.31734165741
slope:-70.86590271190651

In [ ]:
# Predict for new data
new_ages = pd.DataFrame({'Age':[25,30,35,40,45]})
new_salaries = model.predict(new_ages)
print("\nPredicted Salaries for new_age")
for Age,Salary in zip(new_ages['Age'],new_salaries):
  print(f"Age:{Age},Predicted Salary:{Salary:.2f}")

Predicted Salaries for new_age
Age:25,Predicted Salary:76327.67
Age:30,Predicted Salary:75973.34
Age:35,Predicted Salary:75619.01
Age:40,Predicted Salary:75264.68
Age:45,Predicted Salary:74910.35